- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: start the server
  os_server_action:
    server: "hana-cockpit"
    action: start
