- name: execute command to shutdown process
  shell: "/usr/sap/hostctrl/exe/sapcontrol -nr {{ instance_number }} -function Stop"
  become: true
  become_user: root
  ignore_errors: yes
  
- name: Sleep to let process gracefully shutdown
  pause:
    seconds: 60
  
